---
title: "Publishing a Protocol: lived experience"
author: "Martin Law"
date: "2023-11-28"
output: powerpoint_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


PAPMAT, NOTACS STRATOSPHERE, PIPAH

# Why publish the trial protocol?

 - Increased validity;
 - Helps other researchers:
    - Plan study with similar design;
    - Know that this study is taking place and its details (beyond clinicaltrials.gov);
 - Publish or perish! Rare opportunity for applied statisticians to be the first author;
 - May be the only published paper from the study.


# How to publish the trial protocol

 - Choose a journal (spoiler alert: it's *Trials*);
 - Use the journal's template and share it.

# Practical lessons

 - Your CTU's template may be very different to the journal's template, so consider updating your CTU's own templates to match the journal's.
 
 - Start early:
   - If "converting" a protocol to the journal template, this becomes harder the more developed the protocol is.
   - If using the journal template as a guide only, there is still a great deal of work to be done.
   
 - Expect it to take a long time, so...
 
 - Get buy-in from co-authors!

# Authorship

See https://www.icmje.org.

Same criteria as any other published manuscript:
  - Substantial contributions to the conception/design of the work; or the acquisition/analysis/interpretation of data for the work; AND
  - Drafting/critically reviewing the intellectual content; AND
  - Final approval of the version to be published; AND
  - Agreement to be accountable for all aspects of the work. 
  

# Related: The Statistical Analysis Plan

Publish this too! How? For *Trials* at least, in one of the following ways:

 - Directly within the submitted protocol (if trial is simple);
 - As an appendix alongside the submitted protocol;
 - As an "addendum"/update to a published protocol;
 - As a completely separate submission (inc. authors and DOI)





